[package]
name = "splendor-authority"
version.workspace = true
edition.workspace = true

[features]
default = []
secret-provider-test-support = []

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
uuid = { workspace = true }
zeroize = { workspace = true }
splendor-store = { path = "../splendor-store" }
splendor-types = { path = "../splendor-types" }
