[package]
name = "splendor-adapter-secrets-memory"
version.workspace = true
edition.workspace = true
publish = false

[features]
default = []
memory-secret-provider = []

[dependencies]
splendor-authority = { path = "../../crates/splendor-authority" }
splendor-types = { path = "../../crates/splendor-types" }
uuid = { workspace = true }
zeroize = { workspace = true }
